export default {
appLogo: require('./images/appLogo.png'),
financeIllustration: require('./images/financeIllustration.png'),
bag: require('./images/Splashbg.png'),
Loginbg: require('./images/Loginbg.png'),
Mobile: require('./images/Mobile.png'),
appLogo1: require('./images/appLogo1.png'),
right1: require('./images/right1.png'),
Editpen: require('./images/Editpen.png'),
conservativeIcon: require('./images/conservativeIcon.png'),
Conservative: require('./images/Conservative.png'),
eoditphots: require('./images/eoditphots.png'),
lock: require('./images/lock.png'),
ViewSavedPlans: require('./images/ViewSavedPlans.png'),
Calls: require('./images/Calls.png'),
Planning: require('./images/Planning.png'),
hide: require('./images/hide.png'),
moderateIcon: require('./images/moderateIcon.png'),
mess: require('./images/Email.png'),
aggressiveIcon: require('./images/aggressiveIcon.png'),
search1: require('./images/search1.png'),
menus: require('./images/menus.png'),
order: require('./images/order.png'),
pin: require('./images/pin.png'),
Phone1: require('./images/Phone1.png'),
Iconreceiv: require('./images/Iconreceiv.png'),
helpPrva: require('./images/helpPrva.png'),
IconRed: require('./images/IconRed.png'),
Frame: require('./images/Frame.png'),
Location: require('./images/Location.png'),
voies: require('./images/voies.png'),
profiel: require('./images/profiel.png'),
rightaArrow: require('./images/rightaArrow.png'),
earing: require('./images/earing.png'),
calnder: require('./images/calnder.png'),
edit1: require('./images/edit1.png'),
sp2: require('./images/sp2.png'),
Closed: require('./images/Closed.png'),
sp3: require('./images/sp3.png'),
Next: require('./images/Next.png'),
Calblack: require('./images/Calblack.png'),
Accepted: require('./images/Accepted.png'),
Vector: require('./images/Vector.png'),
Notification: require('./images/Notification.png'),
document: require('./images/document.png'),
MessageBlack: require('./images/MessageBlack.png'),
trck: require('./images/trck.png'),
Dots: require('./images/Dots.png'),
arrowqdown: require('./images/arrowqdown.png'),
delite: require('./images/delite.png'),
BlessImage: require('./images/BlessImage.png'),
more_vert: require('./images/more_vert.png'),
NewTasks: require('./images/NewTasks.png'),
addplain: require('./images/addplain.png'),
time: require('./images/time.png'),
ToPickUp: require('./images/ToPickUp.png'),
qolor: require('./images/qolor.png'),
Delivering: require('./images/Delivering.png'),
Completed : require('./images/Completed.png'),
group1 : require('./images/group1.png'),
saveP : require('./images/saveP.png'),

black: require('./images/black.png'),
locationpin2: require('./images/locationpin2.png'),
location1: require('./images/location1.png'),
// group: require('./images/goup2.png'),
group: require('./images/group.png'),
right: require('./images/arrowRight.png'),
Arrived: require('./images/Arrived.png'),
Pin2: require('./images/Pin2.png'),
Icon: require('./images/Icon.png'),
apple: require('./images/apple.png'),
Assigned: require('./images/Assigned.png'),
Delivered: require('./images/Delivered.png'),
MohronFag: require('./images/MohronFag.png'),
prfile: require('./images/prfile.png'),
pushup: require('./images/pushup.png'),
copy: require('./images/copy.png'),
running: require('./images/running.png'),
back: require('./images/back.png'),
wait: require('./images/wait.png'),
arrowDown: require('./images/arrowDown.png'),
logout: require('./images/logout.png'),
Filter: require('./images/Filter.png'),
dounArroww: require('./images/dounArroww.png'),
aboutus: require('./images/aboutus.png'),
BackLeft: require('./images/BackLeft.png'),
OrderPlaced: require('./images/OrderPlaced.png'),
userLogo: require('./images/userLogo.png'),
Base: require('./images/Base.png'),
order2: require('./images/order2.png'),
Optimistic: require('./images/Optimistic.png'),
eye: require('./images/eye.png'),
Delete: require('./images/Delete.png'),




}; 